# Generated by Django 5.1.1 on 2024-10-01 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть введён в корректном формате.', regex='^\\+?(\\d{1,3})?[-.\\s]?\\(?\\d{1,3}\\)?[-.\\s]?\\d{1,3}[-.\\s]?\\d{2,3}[-.\\s]?\\d{2,3}$')], verbose_name='Телефон'),
        ),
    ]
