# Generated by Django 5.1.1 on 2024-10-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('', ''), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='', max_length=2, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, choices=[('', ''), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='', max_length=2, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, choices=[('', ''), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='', max_length=2, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, choices=[('', ''), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='', max_length=2, null=True, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.RenameField(
            model_name='perevalimage',
            old_name='img_path',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='autumn',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='spring',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='summer',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='winter',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.level'),
        ),
    ]
